files:
  - source: /locales/en/common.json
    ignore:
      - /locales/en/banner.json    
      - /locales/en/outfit.json
      - /locales/en/item.json
      - /locales/en/version.json
    translation: /locales/%two_letters_code%/%original_file_name%
