[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22.20.0"
  NODE_OPTIONS = "--max-old-space-size=8192"

[images]
  remote_images = ["https://ik.imagekit.io/gongeous/.*"]