export const ITEM_SEARCH_TAXONOMY_ITEM_TYPES = [
  'hair',
  'dresses',
  'outerwear',
  'tops',
  'bottoms',
  'socks',
  'shoes',
  'hairAccessories',
  'headwear',
  'earrings',
  'neckwear',
  'bracelets',
  'rings',
  'gloves',
  'chokers',
  'chestAccessories',
  'pendants',
  'backpieces',
  'armDecorations',
  'handhelds',
  'faceDecorations',
  'bodyPaint',
] as const

export const ITEM_SEARCH_SUBCATEGORY_PARENT_BY_TYPE = {
  handhelds: {
    axe: 'weapon',
    back_scratcher: 'tool',
    bat: 'weapon',
    birdcage: 'cage',
    bow: 'weapon',
    brush: 'tool',
    candy: 'food',
    clipboard: 'tool',
    clutch: 'handbag',
    crossbow: 'weapon',
    cup: 'drinkware',
    fishing_rod: 'tool',
    flute: 'instrument',
    folding_fan: 'fan',
    fruit: 'food',
    goblet: 'drinkware',
    hammer: 'tool',
    hoe: 'tool',
    ice_cream: 'food',
    maracas: 'instrument',
    mug: 'drinkware',
    musket: 'weapon',
    net: 'tool',
    pipa: 'instrument',
    purse: 'handbag',
    rattle_drum: 'instrument',
    round_fan: 'fan',
    satchel: 'handbag',
    scissors: 'tool',
    spear: 'weapon',
    spellbook: 'book',
    suitcase: 'handbag',
    sword: 'weapon',
    tambourine: 'instrument',
    ukulele: 'instrument',
    violin: 'instrument',
    watering_can: 'tool',
  },
  armDecorations: {
    arm_cuff: 'armlet',
    arm_drape: 'armlet',
    armband: 'armlet',
    tattoo: 'body_paint',
  },
  backpieces: {
    bat_wings: 'wings',
    cape: 'drape',
    capelet: 'drape',
    feathered_wings: 'wings',
    insect_wings: 'wings',
    satchel: 'backpack',
    schoolbag: 'backpack',
    stole: 'drape',
    train: 'drape',
    wide_brim_hat: 'hat',
  },
  bodyPaint: {
    tattoo: 'body_paint',
    wing_effect: 'body_effect',
  },
  bottoms: {
    apron_skirt: 'skirt',
    athletic_shorts: 'shorts',
    bermuda_shorts: 'shorts',
    bib_overalls: 'overalls',
    bloomers: 'shorts',
    cargo_pants: 'pants',
    chaps: 'pants',
    denim_shorts: 'shorts',
    harem_pants: 'pants',
    jeans: 'pants',
    joggers: 'pants',
    ma_mian_skirt: 'skirt',
    overall_shorts: 'overalls',
    overall_skirt: 'overalls',
    palazzo_pants: 'pants',
    ruffle_shorts: 'shorts',
    tailored_shorts: 'shorts',
    wrap_skirt: 'skirt',
  },
  bracelets: {
    bangle: 'bracelet',
    charm_bracelet: 'bracelet',
    scrunchie: 'bracelet',
  },
  chestAccessories: {
    bow_brooch: 'brooch',
    medal: 'brooch',
    pin: 'brooch',
  },
  chokers: {
    bow_tie: 'tie',
    cravat: 'tie',
    necktie: 'tie',
    pendant_choker: 'choker',
    ruff_collar: 'collar',
    strand_necklace: 'necklace',
  },
  dresses: {
    babydoll_dress: 'dress',
    coat_dress: 'dress',
    corset_dress: 'dress',
    gown: 'dress',
    lolita_dress: 'dress',
    maid_dress: 'dress',
    onesie: 'jumpsuit',
    pinafore_dress: 'dress',
    qipao: 'dress',
    romper: 'jumpsuit',
    ruqun: 'dress',
    sailor_dress: 'dress',
    shenyi: 'dress',
    shirt_dress: 'dress',
    slip_dress: 'dress',
    sundress: 'dress',
    sweater_dress: 'dress',
    tea_dress: 'dress',
    tunic_dress: 'dress',
    wrap_dress: 'dress',
  },
  earrings: {
    chandelier_earrings: 'earring',
    drop_earrings: 'earring',
    hoop_earrings: 'earring',
    stud_earrings: 'earring',
  },
  faceDecorations: {
    decorative_blindfold: 'blindfold',
    decorative_eyepatch: 'eyepatch',
    eye_mask: 'mask',
    face_chain: 'face_jewelry',
    full_face_mask: 'mask',
    glasses: 'eyewear',
    goggles: 'eyewear',
    lower_face_mask: 'mask',
    medical_eyepatch: 'eyepatch',
    monocle: 'eyewear',
    mouth_held: 'flower',
    novelty_glasses: 'eyewear',
    ornamental_mask: 'mask',
    sunglasses: 'eyewear',
  },
  gloves: {
    fingerless_gloves: 'gloves',
    gauntlets: 'gloves',
    mittens: 'gloves',
    opera_gloves: 'gloves',
  },
  hair: {
    chignon: 'updo',
    crown_braid: 'braid',
    double_ring_bun: 'updo',
    drill_twin_tails: 'twin_tails',
    flying_immortal_bun: 'updo',
    half_up_braid: 'half_up',
    half_up_bun: 'half_up',
    half_up_ponytail: 'half_up',
    high_bun: 'bun',
    high_ponytail: 'ponytail',
    high_twin_tails: 'twin_tails',
    low_ponytail: 'ponytail',
    low_twin_tails: 'twin_tails',
    side_braid: 'braid',
    side_bun: 'bun',
    side_ponytail: 'ponytail',
    space_buns: 'bun',
    top_knot: 'bun',
    twin_braids: 'braid',
  },
  hairAccessories: {
    bow: 'hair_ornament',
    coronet: 'crown',
    flower: 'hair_ornament',
    hair_comb: 'hair_ornament',
    hairclip: 'hair_ornament',
    hairpin: 'hair_ornament',
    head_chain: 'headpiece',
    horned_headpiece: 'headpiece',
    ribbon: 'hair_ornament',
    sunglasses: 'eyewear',
    tiara: 'crown',
    veil: 'headpiece',
    wreath: 'hair_ornament',
  },
  headwear: {
    animal_ears: 'headpiece',
    aviator_hat: 'hat',
    bandana: 'headpiece',
    baseball_cap: 'hat',
    beanie: 'hat',
    beret: 'hat',
    boater_hat: 'hat',
    bonnet: 'hat',
    bowler_hat: 'hat',
    bucket_hat: 'hat',
    coronet: 'crown',
    cowboy_hat: 'hat',
    crested_helmet: 'helmet',
    fascinator: 'headpiece',
    goggles: 'eyewear',
    hairpin: 'hair_ornament',
    head_chain: 'headpiece',
    headscarf: 'headpiece',
    horned_headpiece: 'headpiece',
    mask: 'headpiece',
    mini_hat: 'hat',
    mushroom_hat: 'hat',
    newsboy_cap: 'hat',
    peaked_cap: 'hat',
    sunglasses: 'eyewear',
    tiara: 'crown',
    top_hat: 'hat',
    tricorn_hat: 'hat',
    veil: 'headpiece',
    visor: 'hat',
    wide_brim_hat: 'hat',
    witch_hat: 'hat',
    wreath: 'hair_ornament',
  },
  neckwear: {
    bib_necklace: 'necklace',
    lariat_necklace: 'necklace',
    lei: 'necklace',
    pendant_choker: 'choker',
    pendant_necklace: 'necklace',
    strand_necklace: 'necklace',
  },
  outerwear: {
    beizi: 'robe',
    blazer: 'jacket',
    bolero: 'jacket',
    bomber_jacket: 'jacket',
    capelet: 'cape',
    cloak: 'cape',
    daxiushan: 'robe',
    fur_coat: 'coat',
    hooded_cape: 'cape',
    hooded_vest: 'vest',
    hoodie: 'jacket',
    long_cardigan: 'cardigan',
    military_jacket: 'jacket',
    poncho: 'cape',
    shirt_jacket: 'jacket',
    shrug: 'cardigan',
    stole: 'shawl',
    waistcoat: 'vest',
    windbreaker: 'jacket',
  },
  pendants: {
    calf_garter: 'garter',
    crossbody_bag: 'bag',
    shoulder_bag: 'bag',
    thigh_garter: 'garter',
  },
  rings: {
    ring_set: 'ring',
  },
  shoes: {
    ankle_strap_heels: 'heels',
    ballet_flats: 'flats',
    clogs: 'mules',
    combat_boots: 'boots',
    cowboy_boots: 'boots',
    dorsay_heels: 'heels',
    gladiator_sandals: 'sandals',
    high_top_sneakers: 'sneakers',
    lace_up_flats: 'flats',
    low_top_sneakers: 'sneakers',
    penny_loafers: 'loafers',
    pumps: 'heels',
    riding_boots: 'boots',
    slingback_heels: 'heels',
    t_strap_heels: 'heels',
    traditional_chinese_flats: 'flats',
  },
  socks: {
    garter_stockings: 'stockings',
    pantyhose: 'tights',
  },
  tops: {
    bandeau_top: 'tube_top',
    bralette: 'camisole',
    bustier: 'corset',
    button_up_shirt: 'shirt',
    hanfu_top: 'blouse',
    hoodie: 'sweatshirt',
    leotard: 'bodysuit',
    maid_blouse: 'blouse',
    military_jacket: 'jacket',
    milkmaid_top: 'blouse',
    peasant_blouse: 'blouse',
    polo_shirt: 'shirt',
    sailor_blouse: 'blouse',
    school_uniform_blouse: 'blouse',
    tailored_jacket: 'jacket',
    track_jacket: 'jacket',
  },
} as const
